name: "Build Flutter Web and Push Release"

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build Flutter Web and Push Release
    runs-on: macos-latest  # You can change this to ubuntu-latest if you prefer Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web  # Build the Flutter web app

      - name: Zip the build files
        run: |
          cd build/web
          zip -r $GITHUB_WORKSPACE/flutter_web_build.zip *  # Zips the build/web folder

      - name: Push to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: $GITHUB_WORKSPACE/flutter_web_build.zip  # Path to the zip file
          tag: v1.0.${{ github.run_number }}  # Automatically generate a version number (e.g., v1.0.1)
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
